[[news]]
date = "2025-09"
content = "保送至中国科学技术大学信息科学技术学院攻读硕士研究生。"

[[news]]
date = "2025-06"
content = "获哈尔滨工程大学优秀毕业生及黑龙江省优秀毕业生。"

[[news]]
date = "2024-07"
content = "获中国大学生服务外包创新创业大赛国家级三等奖。"

[[news]]
date = "2024-05"
content = "国家级大学生创新创业训练计划项目顺利结题。"

[[news]]
date = "2023-08"
content = "获中国大学生计算机设计大赛国家级三等奖。"

[[news]]
date = "2022-10"
content = "获国家奖学金（全国前 0.2%）。"
